<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="DashBoard.aspx.cs" Inherits="Hotel_Management.DashBoard" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link rel="stylesheet" type="text/css" href="Styles/dashboard.css" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="wlcm">
    <h1>DashBoard</h1>
    <asp:Label CssClass="lblwel" ID="welcome" runat="server" Text="Welcome   " Width="49%" Height="41px"></asp:Label>
        </div>
    <div class="dash">
        <div><asp:Label ID="lblname" CssClass="lbl" runat="server" Text="Full Name :"></asp:Label>
        <asp:Label CssClass="value" ID="name" runat="server" Text="Full Name :"></asp:Label>  </div>
        <div><asp:Label ID="lblusername" CssClass="lbl" runat="server" Text="UserName :"></asp:Label>
        <asp:Label CssClass="value" ID="username" runat="server" Text="UserName :"></asp:Label> </div>
        <div><asp:Label ID="lblgender" CssClass="lbl" runat="server" Text="Gender :"> </asp:Label>
        <asp:Label CssClass="value" ID="gender" runat="server" Text="Gender :"> </asp:Label> </div>
        <div><asp:Label ID="lblemail" CssClass="lbl" runat="server" Text="Email :"> </asp:Label>
        <asp:Label CssClass="value" ID="email" runat="server" Text="Email :"> </asp:Label> </div>
        <div><asp:Label ID="lblPhone" CssClass="lbl" runat="server" Text="Phone :">  </asp:Label>
        <asp:Label CssClass="value" ID="phone" runat="server" Text="Phone :">  </asp:Label> </div>
        <div><asp:Label ID="lbladdress" CssClass="lbl" runat="server" Text="Address :"> </asp:Label>
        <asp:Label CssClass="value" ID="address" runat="server" Text="Address :"> </asp:Label> </div>
        <div><asp:Label ID="lblage" CssClass="lbl" runat="server" Text="Age :"> </asp:Label>
        <asp:Label CssClass="value" ID="age" runat="server" Text="Age :"> </asp:Label> </div>
        <div><asp:Label ID="lbllang" CssClass="lbl" runat="server" Text="Languages Known :">  </asp:Label>
        <asp:Label CssClass="value" ID="lang" runat="server" Text="Languages Known :">  </asp:Label> </div>
        <div><asp:Label ID="lblcountry" CssClass="lbl" runat="server" Text="Country :">  </asp:Label>
        <asp:Label CssClass="value" ID="country" runat="server" Text="Country :">  </asp:Label> </div>

    </div>
    <div>

         <div class="wlcm">
 <h2>Details of all registered users !!</h2>
     </div>

    <form id="dshbrd" runat="server">

        <asp:GridView CssClass="gv" ID="UsrDtls" runat="server" AllowPaging="true" PageSize="5" PagerStyle-CssClass="pager" PagerStyle-HorizontalAlign="Center"  AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateColumns="False" BackColor="#21BEB3" BorderColor="#336666" BorderStyle="Double" BorderWidth="3px" CellPadding="4" CellSpacing="1" ForeColor="#006666" OnRowDeleting="UsrDtls_RowDeleting" OnRowEditing="UsrDtls_RowEditing" OnRowCancelingEdit="UsrDtls_RowCancelingEdit" OnRowUpdating="UsrDtls_RowUpdating" OnPageIndexChanging="UsrDtls_PageIndexChanging">
            <Columns>
                <asp:TemplateField HeaderText="First Name">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("Fname") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("Fname") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Last Name">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("Lname") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("Lname") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Username">
                    <EditItemTemplate>
                        <asp:Label ID="TextBox3" runat="server" Text='<%# Bind("Uname") %>'></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("Uname") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Gender">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox4" runat="server" Text='<%# Bind("Gender") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label4" runat="server" Text='<%# Bind("Gender") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Password">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox5" runat="server" Text='<%# Bind("Password") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label5" runat="server" Text='<%# Bind("Password") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Email">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox6" runat="server" Text='<%# Bind("Email") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label6" runat="server" Text='<%# Bind("Email") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Phone Number">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox7" runat="server" Text='<%# Bind("Phone") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label7" runat="server" Text='<%# Bind("Phone") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Address">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox8" runat="server" Text='<%# Bind("Address") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label8" runat="server" Text='<%# Bind("Address") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Age">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox9" runat="server" Text='<%# Bind("Age") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label9" runat="server" Text='<%# Bind("Age") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Language">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox10" runat="server" Text='<%# Bind("Lang") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label10" runat="server" Text='<%# Bind("Lang") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Country">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox11" runat="server" Text='<%# Bind("Country") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label11" runat="server" Text='<%# Bind("Country") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
            <FooterStyle BackColor="White" ForeColor="#333333" />
            <HeaderStyle BackColor="#336666" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#336666" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="White" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#339966" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F7F7F7" />
            <SortedAscendingHeaderStyle BackColor="#487575" />
            <SortedDescendingCellStyle BackColor="#E5E5E5" />
            <SortedDescendingHeaderStyle BackColor="#275353" />
        </asp:GridView>
        <br />
        <asp:Label ID="excpn" runat="server" ForeColor="#FF6600" Text="Label" Visible="False"></asp:Label>
        </form>
    </div>

</asp:Content>
