<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="HotelDetails.aspx.cs" Inherits="Hotel_Management.HotelDetails" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link rel="stylesheet" type="text/css" href="Styles/booked.css" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
   <div id="welcome">
    <h1>Your Booked Rooms Details</h1>
        <asp:Label ID="lblusrnm" runat="server" Text="These are the Hotels Rooms which are booked by "></asp:Label>
        <asp:Label ID="usrnm" runat="server" Text="Username"> </asp:Label>
       </div> 
    <div  class="rcont" > 
       <asp:Label ID="rooms" runat="server" Text="Label" Visible="False"></asp:Label>
        <asp:Repeater ID="Repeater1" runat="server">
    <ItemTemplate>
        <div class="repeater" >
           <div> <strong>Room Type : </strong> <%# Eval("Roomtype") %> </div>
     <div>       <strong>Amenities : </strong> <%# Eval("Amenities") %> </div>
        </div>
    </ItemTemplate>
</asp:Repeater>

    </div>

    <h2 id="welcome">All Booked Rooms Details !!</h2>

    <div>
    <form id="rmdtlsfrm" runat="server">
        <asp:GridView CssClass="gv" ID="RmDtls" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateColumns="False" BackColor="#3333CC" BorderColor="#0033CC" BorderStyle="Ridge" BorderWidth="2px" CellPadding="20" CellSpacing="8" GridLines="None" OnRowDeleting="RmDtls_RowDeleting" OnRowCancelingEdit="RmDtls_RowCancelingEdit" OnRowEditing="RmDtls_RowEditing" OnRowUpdating="RmDtls_RowUpdating">
            <Columns>
                <asp:TemplateField HeaderText="Username">
                    <EditItemTemplate>
                        <asp:Label ID="TextBox1" runat="server" Text='<%# Bind("Uname") %>'></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("Uname") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Room Type">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("Roomtype") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("Roomtype") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Amenities">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("Amenities") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("Amenities") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
            <FooterStyle BackColor="#C6C3C6" ForeColor="Black" />
            <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#E7E7FF" />
            <PagerStyle BackColor="#C6C3C6" ForeColor="Black" HorizontalAlign="Right" />
            <RowStyle BackColor="#DEDFDE" ForeColor="Black" />
            <SelectedRowStyle BackColor="#9471DE" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#594B9C" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#33276A" />
        </asp:GridView>
        <br />
        <asp:Label ID="excpn" runat="server" ForeColor="#FF6600" Text="Label" Visible="False"></asp:Label>
        </form>
    </div>
</asp:Content>
